import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { generateRawValidator, generateZodValidator } from '../src/generator.ts';

const keys = ['DATABASE_URL', 'JWT_SECRET', 'PORT'];

describe('generateZodValidator', () => {
  it('includes zod import', () => {
    const output = generateZodValidator(keys);
    assert.ok(output.includes("import { z } from 'zod'"));
  });

  it('generates z.object with all keys', () => {
    const output = generateZodValidator(keys);
    assert.ok(output.includes('DATABASE_URL: z.string().min(1,'));
    assert.ok(output.includes('JWT_SECRET: z.string().min(1,'));
    assert.ok(output.includes('PORT: z.string().min(1,'));
  });

  it('includes envSchema.parse and Env type export', () => {
    const output = generateZodValidator(keys);
    assert.ok(output.includes('envSchema.parse(process.env)'));
    assert.ok(output.includes('export type Env = z.infer<typeof envSchema>'));
  });

  it('includes dotenv import when withDotenvLoad is true', () => {
    const output = generateZodValidator(keys, { withDotenvLoad: true });
    assert.ok(output.includes("import 'dotenv/config'"));
  });

  it('does not include dotenv import by default', () => {
    const output = generateZodValidator(keys);
    assert.ok(!output.includes('dotenv'));
  });

  it('includes auto-generated comment', () => {
    const output = generateZodValidator(keys);
    assert.ok(output.includes('Auto-generated by env-validator-gen'));
  });

  it('handles empty keys array', () => {
    const output = generateZodValidator([]);
    assert.ok(output.includes('z.object({'));
    assert.ok(output.includes('});'));
  });
});

describe('generateRawValidator', () => {
  it('generates REQUIRED_ENV_VARS array with all keys', () => {
    const output = generateRawValidator(keys);
    assert.ok(output.includes("'DATABASE_URL'"));
    assert.ok(output.includes("'JWT_SECRET'"));
    assert.ok(output.includes("'PORT'"));
  });

  it('includes missing check and process.exit(1)', () => {
    const output = generateRawValidator(keys);
    assert.ok(output.includes('missing.length > 0'));
    assert.ok(output.includes('process.exit(1)'));
  });

  it('exports env as typed Record', () => {
    const output = generateRawValidator(keys);
    assert.ok(output.includes('export const env = process.env'));
  });

  it('includes auto-generated comment', () => {
    const output = generateRawValidator(keys);
    assert.ok(output.includes('Auto-generated by env-validator-gen'));
  });

  it('does not include zod', () => {
    const output = generateRawValidator(keys);
    assert.ok(!output.includes('zod'));
  });
});
