export interface GeneratorOptions {
  withDotenvLoad?: boolean;
}

export function generateZodValidator(keys: string[], opts: GeneratorOptions = {}): string {
  const lines: string[] = [
    '// Auto-generated by env-validator-gen. Do not edit manually.',
    "import { z } from 'zod';",
  ];

  if (opts.withDotenvLoad) {
    lines.push("import 'dotenv/config';");
  }

  lines.push('', 'const envSchema = z.object({');

  for (const key of keys) {
    lines.push(`  ${key}: z.string().min(1, '${key} is required'),`);
  }

  lines.push('});', '');
  lines.push('export const env = envSchema.parse(process.env);');
  lines.push('export type Env = z.infer<typeof envSchema>;', '');

  return lines.join('\n');
}

export function generateRawValidator(keys: string[]): string {
  const lines: string[] = [
    '// Auto-generated by env-validator-gen. Do not edit manually.',
    '',
    'const REQUIRED_ENV_VARS = [',
  ];

  for (const key of keys) {
    lines.push(`  '${key}',`);
  }

  lines.push('] as const;', '');
  lines.push('const missing = REQUIRED_ENV_VARS.filter((k) => !process.env[k]);');
  lines.push('');
  lines.push('if (missing.length > 0) {');
  lines.push("  console.error(`Missing required environment variables: ${missing.join(', ')}`);");
  lines.push('  process.exit(1);');
  lines.push('}');
  lines.push('');
  lines.push('export const env = process.env as Record<typeof REQUIRED_ENV_VARS[number], string>;', '');

  return lines.join('\n');
}
